const String SHARED_PREFERENCES_KEY_AUTHORIZATION_KEY = 'authKey';
const String SHARED_PREFERENCES_KEY_TIMELINE_LENGTH = 'timelineLength';
const String SHARED_PREFERENCES_UNSET_AUTHORIZATION_KEY = '';
const int SHARED_PREFERENCES_DEFAULT_TIMELINE_LENGTH = 20;

const REQUEST_HEADER_AUTHORIZATION = 'Authorization';
const REQUEST_HEADER_AUTHORIZATION_PREFIX = 'Bearer ';
